# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.CharField(default='0', max_length=20)),
                ('img_url', models.CharField(max_length=255)),
                ('description', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerbingo.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerbingo.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_user_set', through='beerbingo.Like', to='beerbingo.User'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerbingo.Item'),
        ),
    ]
